# record example from kaggle csv
VALID_CLAIM_RECORD = {
    "months_as_customer": "328",
    "age": "48",
    "policy_number": "521585",
    "policy_bind_date": "2014-10-17",
    "policy_state": "OH",
    "policy_csl": "250/500",
    "policy_deductable": "1000",
    "policy_annual_premium": "1406.91",
    "umbrella_limit": "0",
    "insured_zip": "466132",
    "insured_sex": "MALE",
    "insured_education_level": "MD",
    "insured_occupation": "craft-repair",
    "insured_hobbies": "sleeping",
    "insured_relationship": "husband",
    "capital-gains": "53300",
    "capital-loss": "0",
    "incident_date": "2015-01-25",
    "incident_type": "Single Vehicle Collision",
    "collision_type": "Side Collision",
    "incident_severity": "Major Damage",
    "authorities_contacted": "Police",
    "incident_state": "SC",
    "incident_city": "Columbus",
    "incident_location": "9935 4th Drive",
    "incident_hour_of_the_day": "5",
    "number_of_vehicles_involved": "1",
    "property_damage": "YES",
    "bodily_injuries": "1",
    "witnesses": "2",
    "police_report_available": "YES",
    "total_claim_amount": "71610",
    "injury_claim": "6510",
    "property_claim": "13020",
    "vehicle_claim": "52080",
    "auto_make": "Saab",
    "auto_model": "92x",
    "auto_year": "2004",
    "fraud_reported": "Y",
    "_c39": "",
}